// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"io"
	"monzoCrawler/domain/crawlerPool"
	"monzoCrawler/domain/model"
	"net/url"
	"sync"
)

// Ensure, that FetcherExtractorMock does implement crawlerPool.FetcherExtractor.
// If this is not the case, regenerate this file with moq.
var _ crawlerPool.FetcherExtractor = &FetcherExtractorMock{}

// FetcherExtractorMock is a mock implementation of crawlerPool.FetcherExtractor.
//
// 	func TestSomethingThatUsesFetcherExtractor(t *testing.T) {
//
// 		// make and configure a mocked crawlerPool.FetcherExtractor
// 		mockedFetcherExtractor := &FetcherExtractorMock{
// 			ExtractFunc: func(reader io.Reader) (model.CrawlResult, error) {
// 				panic("mock out the Extract method")
// 			},
// 			FetchFunc: func(ctx context.Context, urlMoqParam url.URL) (io.ReadCloser, error) {
// 				panic("mock out the Fetch method")
// 			},
// 		}
//
// 		// use mockedFetcherExtractor in code that requires crawlerPool.FetcherExtractor
// 		// and then make assertions.
//
// 	}
type FetcherExtractorMock struct {
	// ExtractFunc mocks the Extract method.
	ExtractFunc func(reader io.Reader) (model.CrawlResult, error)

	// FetchFunc mocks the Fetch method.
	FetchFunc func(ctx context.Context, urlMoqParam url.URL) (io.ReadCloser, error)

	// calls tracks calls to the methods.
	calls struct {
		// Extract holds details about calls to the Extract method.
		Extract []struct {
			// Reader is the reader argument value.
			Reader io.Reader
		}
		// Fetch holds details about calls to the Fetch method.
		Fetch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UrlMoqParam is the urlMoqParam argument value.
			UrlMoqParam url.URL
		}
	}
	lockExtract sync.RWMutex
	lockFetch   sync.RWMutex
}

// Extract calls ExtractFunc.
func (mock *FetcherExtractorMock) Extract(reader io.Reader) (model.CrawlResult, error) {
	if mock.ExtractFunc == nil {
		panic("FetcherExtractorMock.ExtractFunc: method is nil but FetcherExtractor.Extract was just called")
	}
	callInfo := struct {
		Reader io.Reader
	}{
		Reader: reader,
	}
	mock.lockExtract.Lock()
	mock.calls.Extract = append(mock.calls.Extract, callInfo)
	mock.lockExtract.Unlock()
	return mock.ExtractFunc(reader)
}

// ExtractCalls gets all the calls that were made to Extract.
// Check the length with:
//     len(mockedFetcherExtractor.ExtractCalls())
func (mock *FetcherExtractorMock) ExtractCalls() []struct {
	Reader io.Reader
} {
	var calls []struct {
		Reader io.Reader
	}
	mock.lockExtract.RLock()
	calls = mock.calls.Extract
	mock.lockExtract.RUnlock()
	return calls
}

// Fetch calls FetchFunc.
func (mock *FetcherExtractorMock) Fetch(ctx context.Context, urlMoqParam url.URL) (io.ReadCloser, error) {
	if mock.FetchFunc == nil {
		panic("FetcherExtractorMock.FetchFunc: method is nil but FetcherExtractor.Fetch was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		UrlMoqParam url.URL
	}{
		Ctx:         ctx,
		UrlMoqParam: urlMoqParam,
	}
	mock.lockFetch.Lock()
	mock.calls.Fetch = append(mock.calls.Fetch, callInfo)
	mock.lockFetch.Unlock()
	return mock.FetchFunc(ctx, urlMoqParam)
}

// FetchCalls gets all the calls that were made to Fetch.
// Check the length with:
//     len(mockedFetcherExtractor.FetchCalls())
func (mock *FetcherExtractorMock) FetchCalls() []struct {
	Ctx         context.Context
	UrlMoqParam url.URL
} {
	var calls []struct {
		Ctx         context.Context
		UrlMoqParam url.URL
	}
	mock.lockFetch.RLock()
	calls = mock.calls.Fetch
	mock.lockFetch.RUnlock()
	return calls
}
